// Code generated by go-swagger; DO NOT EDIT.

package prospects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/graphql-editor/woodpecker-go/models"
)

// GetProspectsReader is a Reader for the GetProspects structure.
type GetProspectsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetProspectsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetProspectsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewGetProspectsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetProspectsOK creates a GetProspectsOK with default headers values
func NewGetProspectsOK() *GetProspectsOK {
	return &GetProspectsOK{}
}

/* GetProspectsOK describes a response with status code 200, with default header values.

An array of prospects
*/
type GetProspectsOK struct {
	Payload []*models.Prospect
}

func (o *GetProspectsOK) Error() string {
	return fmt.Sprintf("[GET /prospects][%d] getProspectsOK  %+v", 200, o.Payload)
}
func (o *GetProspectsOK) GetPayload() []*models.Prospect {
	return o.Payload
}

func (o *GetProspectsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetProspectsDefault creates a GetProspectsDefault with default headers values
func NewGetProspectsDefault(code int) *GetProspectsDefault {
	return &GetProspectsDefault{
		_statusCode: code,
	}
}

/* GetProspectsDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type GetProspectsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the get prospects default response
func (o *GetProspectsDefault) Code() int {
	return o._statusCode
}

func (o *GetProspectsDefault) Error() string {
	return fmt.Sprintf("[GET /prospects][%d] GetProspects default  %+v", o._statusCode, o.Payload)
}
func (o *GetProspectsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *GetProspectsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
