// Code generated by go-swagger; DO NOT EDIT.

package prospects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/graphql-editor/woodpecker-go/models"
)

// PostAddProspectsListReader is a Reader for the PostAddProspectsList structure.
type PostAddProspectsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAddProspectsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAddProspectsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostAddProspectsListDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostAddProspectsListOK creates a PostAddProspectsListOK with default headers values
func NewPostAddProspectsListOK() *PostAddProspectsListOK {
	return &PostAddProspectsListOK{}
}

/* PostAddProspectsListOK describes a response with status code 200, with default header values.

The created prospect
*/
type PostAddProspectsListOK struct {
	Payload *models.CreateProspectResponse
}

func (o *PostAddProspectsListOK) Error() string {
	return fmt.Sprintf("[POST /add_prospects_list][%d] postAddProspectsListOK  %+v", 200, o.Payload)
}
func (o *PostAddProspectsListOK) GetPayload() *models.CreateProspectResponse {
	return o.Payload
}

func (o *PostAddProspectsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateProspectResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAddProspectsListDefault creates a PostAddProspectsListDefault with default headers values
func NewPostAddProspectsListDefault(code int) *PostAddProspectsListDefault {
	return &PostAddProspectsListDefault{
		_statusCode: code,
	}
}

/* PostAddProspectsListDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type PostAddProspectsListDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post add prospects list default response
func (o *PostAddProspectsListDefault) Code() int {
	return o._statusCode
}

func (o *PostAddProspectsListDefault) Error() string {
	return fmt.Sprintf("[POST /add_prospects_list][%d] PostAddProspectsList default  %+v", o._statusCode, o.Payload)
}
func (o *PostAddProspectsListDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostAddProspectsListDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
