// Code generated by go-swagger; DO NOT EDIT.

package prospects

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/graphql-editor/woodpecker/models"
)

// PostAddProspectsCampaignReader is a Reader for the PostAddProspectsCampaign structure.
type PostAddProspectsCampaignReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAddProspectsCampaignReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAddProspectsCampaignOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostAddProspectsCampaignDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostAddProspectsCampaignOK creates a PostAddProspectsCampaignOK with default headers values
func NewPostAddProspectsCampaignOK() *PostAddProspectsCampaignOK {
	return &PostAddProspectsCampaignOK{}
}

/* PostAddProspectsCampaignOK describes a response with status code 200, with default header values.

The created prospect
*/
type PostAddProspectsCampaignOK struct {
	Payload *models.CreateProspectResponse
}

func (o *PostAddProspectsCampaignOK) Error() string {
	return fmt.Sprintf("[POST /add_prospects_campaign][%d] postAddProspectsCampaignOK  %+v", 200, o.Payload)
}
func (o *PostAddProspectsCampaignOK) GetPayload() *models.CreateProspectResponse {
	return o.Payload
}

func (o *PostAddProspectsCampaignOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateProspectResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostAddProspectsCampaignDefault creates a PostAddProspectsCampaignDefault with default headers values
func NewPostAddProspectsCampaignDefault(code int) *PostAddProspectsCampaignDefault {
	return &PostAddProspectsCampaignDefault{
		_statusCode: code,
	}
}

/* PostAddProspectsCampaignDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type PostAddProspectsCampaignDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post add prospects campaign default response
func (o *PostAddProspectsCampaignDefault) Code() int {
	return o._statusCode
}

func (o *PostAddProspectsCampaignDefault) Error() string {
	return fmt.Sprintf("[POST /add_prospects_campaign][%d] PostAddProspectsCampaign default  %+v", o._statusCode, o.Payload)
}
func (o *PostAddProspectsCampaignDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostAddProspectsCampaignDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
