// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewDeleteProspectsParams creates a new DeleteProspectsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteProspectsParams() *DeleteProspectsParams {
	return &DeleteProspectsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteProspectsParamsWithTimeout creates a new DeleteProspectsParams object
// with the ability to set a timeout on a request.
func NewDeleteProspectsParamsWithTimeout(timeout time.Duration) *DeleteProspectsParams {
	return &DeleteProspectsParams{
		timeout: timeout,
	}
}

// NewDeleteProspectsParamsWithContext creates a new DeleteProspectsParams object
// with the ability to set a context for a request.
func NewDeleteProspectsParamsWithContext(ctx context.Context) *DeleteProspectsParams {
	return &DeleteProspectsParams{
		Context: ctx,
	}
}

// NewDeleteProspectsParamsWithHTTPClient creates a new DeleteProspectsParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteProspectsParamsWithHTTPClient(client *http.Client) *DeleteProspectsParams {
	return &DeleteProspectsParams{
		HTTPClient: client,
	}
}

/* DeleteProspectsParams contains all the parameters to send to the API endpoint
   for the delete prospects operation.

   Typically these are written to a http.Request.
*/
type DeleteProspectsParams struct {

	/* CampaignID.

	   Prospect campaign's ID

	   Format: int32
	*/
	CampaignID *int32

	/* ID.

	   Prospect's ID

	   Format: int32
	*/
	ID int32

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete prospects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProspectsParams) WithDefaults() *DeleteProspectsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete prospects params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteProspectsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete prospects params
func (o *DeleteProspectsParams) WithTimeout(timeout time.Duration) *DeleteProspectsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete prospects params
func (o *DeleteProspectsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete prospects params
func (o *DeleteProspectsParams) WithContext(ctx context.Context) *DeleteProspectsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete prospects params
func (o *DeleteProspectsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete prospects params
func (o *DeleteProspectsParams) WithHTTPClient(client *http.Client) *DeleteProspectsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete prospects params
func (o *DeleteProspectsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCampaignID adds the campaignID to the delete prospects params
func (o *DeleteProspectsParams) WithCampaignID(campaignID *int32) *DeleteProspectsParams {
	o.SetCampaignID(campaignID)
	return o
}

// SetCampaignID adds the campaignId to the delete prospects params
func (o *DeleteProspectsParams) SetCampaignID(campaignID *int32) {
	o.CampaignID = campaignID
}

// WithID adds the id to the delete prospects params
func (o *DeleteProspectsParams) WithID(id int32) *DeleteProspectsParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete prospects params
func (o *DeleteProspectsParams) SetID(id int32) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteProspectsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CampaignID != nil {

		// query param campaign_id
		var qrCampaignID int32

		if o.CampaignID != nil {
			qrCampaignID = *o.CampaignID
		}
		qCampaignID := swag.FormatInt32(qrCampaignID)
		if qCampaignID != "" {

			if err := r.SetQueryParam("campaign_id", qCampaignID); err != nil {
				return err
			}
		}
	}

	// query param id
	qrID := o.ID
	qID := swag.FormatInt32(qrID)
	if qID != "" {

		if err := r.SetQueryParam("id", qID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
