// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new operations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for operations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientOption is the option for Client methods
type ClientOption func(*runtime.ClientOperation)

// ClientService is the interface for Client methods
type ClientService interface {
	DeleteProspects(params *DeleteProspectsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProspectsOK, error)

	PostStopFollowups(params *PostStopFollowupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostStopFollowupsOK, error)

	PostWebhooksSubscribe(params *PostWebhooksSubscribeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostWebhooksSubscribeOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
  DeleteProspects gets the list of prospects

  get the list of prospects

*/
func (a *Client) DeleteProspects(params *DeleteProspectsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*DeleteProspectsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteProspectsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "DeleteProspects",
		Method:             "DELETE",
		PathPattern:        "/prospects",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteProspectsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*DeleteProspectsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*DeleteProspectsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  PostStopFollowups changes prospect status to b l a c k l i s t
*/
func (a *Client) PostStopFollowups(params *PostStopFollowupsParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostStopFollowupsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostStopFollowupsParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostStopFollowups",
		Method:             "POST",
		PathPattern:        "/stop_followups",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostStopFollowupsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostStopFollowupsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PostStopFollowupsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
  PostWebhooksSubscribe post webhooks subscribe API
*/
func (a *Client) PostWebhooksSubscribe(params *PostWebhooksSubscribeParams, authInfo runtime.ClientAuthInfoWriter, opts ...ClientOption) (*PostWebhooksSubscribeOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPostWebhooksSubscribeParams()
	}
	op := &runtime.ClientOperation{
		ID:                 "PostWebhooksSubscribe",
		Method:             "POST",
		PathPattern:        "/webhooks/subscribe",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PostWebhooksSubscribeReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	}
	for _, opt := range opts {
		opt(op)
	}

	result, err := a.transport.Submit(op)
	if err != nil {
		return nil, err
	}
	success, ok := result.(*PostWebhooksSubscribeOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*PostWebhooksSubscribeDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
