// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPostStopFollowupsParams creates a new PostStopFollowupsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostStopFollowupsParams() *PostStopFollowupsParams {
	return &PostStopFollowupsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostStopFollowupsParamsWithTimeout creates a new PostStopFollowupsParams object
// with the ability to set a timeout on a request.
func NewPostStopFollowupsParamsWithTimeout(timeout time.Duration) *PostStopFollowupsParams {
	return &PostStopFollowupsParams{
		timeout: timeout,
	}
}

// NewPostStopFollowupsParamsWithContext creates a new PostStopFollowupsParams object
// with the ability to set a context for a request.
func NewPostStopFollowupsParamsWithContext(ctx context.Context) *PostStopFollowupsParams {
	return &PostStopFollowupsParams{
		Context: ctx,
	}
}

// NewPostStopFollowupsParamsWithHTTPClient creates a new PostStopFollowupsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostStopFollowupsParamsWithHTTPClient(client *http.Client) *PostStopFollowupsParams {
	return &PostStopFollowupsParams{
		HTTPClient: client,
	}
}

/* PostStopFollowupsParams contains all the parameters to send to the API endpoint
   for the post stop followups operation.

   Typically these are written to a http.Request.
*/
type PostStopFollowupsParams struct {

	// Body.
	Body PostStopFollowupsBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post stop followups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostStopFollowupsParams) WithDefaults() *PostStopFollowupsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post stop followups params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostStopFollowupsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post stop followups params
func (o *PostStopFollowupsParams) WithTimeout(timeout time.Duration) *PostStopFollowupsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post stop followups params
func (o *PostStopFollowupsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post stop followups params
func (o *PostStopFollowupsParams) WithContext(ctx context.Context) *PostStopFollowupsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post stop followups params
func (o *PostStopFollowupsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post stop followups params
func (o *PostStopFollowupsParams) WithHTTPClient(client *http.Client) *PostStopFollowupsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post stop followups params
func (o *PostStopFollowupsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post stop followups params
func (o *PostStopFollowupsParams) WithBody(body PostStopFollowupsBody) *PostStopFollowupsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post stop followups params
func (o *PostStopFollowupsParams) SetBody(body PostStopFollowupsBody) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostStopFollowupsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
