// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/graphql-editor/woodpecker/models"
)

// PostWebhooksSubscribeReader is a Reader for the PostWebhooksSubscribe structure.
type PostWebhooksSubscribeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostWebhooksSubscribeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostWebhooksSubscribeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostWebhooksSubscribeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostWebhooksSubscribeOK creates a PostWebhooksSubscribeOK with default headers values
func NewPostWebhooksSubscribeOK() *PostWebhooksSubscribeOK {
	return &PostWebhooksSubscribeOK{}
}

/* PostWebhooksSubscribeOK describes a response with status code 200, with default header values.

The created prospect
*/
type PostWebhooksSubscribeOK struct {
}

func (o *PostWebhooksSubscribeOK) Error() string {
	return fmt.Sprintf("[POST /webhooks/subscribe][%d] postWebhooksSubscribeOK ", 200)
}

func (o *PostWebhooksSubscribeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPostWebhooksSubscribeDefault creates a PostWebhooksSubscribeDefault with default headers values
func NewPostWebhooksSubscribeDefault(code int) *PostWebhooksSubscribeDefault {
	return &PostWebhooksSubscribeDefault{
		_statusCode: code,
	}
}

/* PostWebhooksSubscribeDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type PostWebhooksSubscribeDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post webhooks subscribe default response
func (o *PostWebhooksSubscribeDefault) Code() int {
	return o._statusCode
}

func (o *PostWebhooksSubscribeDefault) Error() string {
	return fmt.Sprintf("[POST /webhooks/subscribe][%d] PostWebhooksSubscribe default  %+v", o._statusCode, o.Payload)
}
func (o *PostWebhooksSubscribeDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostWebhooksSubscribeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
