// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/graphql-editor/woodpecker/models"
)

// PostStopFollowupsReader is a Reader for the PostStopFollowups structure.
type PostStopFollowupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostStopFollowupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostStopFollowupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewPostStopFollowupsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewPostStopFollowupsOK creates a PostStopFollowupsOK with default headers values
func NewPostStopFollowupsOK() *PostStopFollowupsOK {
	return &PostStopFollowupsOK{}
}

/* PostStopFollowupsOK describes a response with status code 200, with default header values.

The created prospect
*/
type PostStopFollowupsOK struct {
	Payload *models.Status
}

func (o *PostStopFollowupsOK) Error() string {
	return fmt.Sprintf("[POST /stop_followups][%d] postStopFollowupsOK  %+v", 200, o.Payload)
}
func (o *PostStopFollowupsOK) GetPayload() *models.Status {
	return o.Payload
}

func (o *PostStopFollowupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Status)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostStopFollowupsDefault creates a PostStopFollowupsDefault with default headers values
func NewPostStopFollowupsDefault(code int) *PostStopFollowupsDefault {
	return &PostStopFollowupsDefault{
		_statusCode: code,
	}
}

/* PostStopFollowupsDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type PostStopFollowupsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the post stop followups default response
func (o *PostStopFollowupsDefault) Code() int {
	return o._statusCode
}

func (o *PostStopFollowupsDefault) Error() string {
	return fmt.Sprintf("[POST /stop_followups][%d] PostStopFollowups default  %+v", o._statusCode, o.Payload)
}
func (o *PostStopFollowupsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *PostStopFollowupsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostStopFollowupsBody post stop followups body
swagger:model PostStopFollowupsBody
*/
type PostStopFollowupsBody struct {

	// prospect
	Prospect *PostStopFollowupsParamsBodyProspect `json:"prospect,omitempty"`
}

// Validate validates this post stop followups body
func (o *PostStopFollowupsBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateProspect(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostStopFollowupsBody) validateProspect(formats strfmt.Registry) error {
	if swag.IsZero(o.Prospect) { // not required
		return nil
	}

	if o.Prospect != nil {
		if err := o.Prospect.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "prospect")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "prospect")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this post stop followups body based on the context it is used
func (o *PostStopFollowupsBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateProspect(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostStopFollowupsBody) contextValidateProspect(ctx context.Context, formats strfmt.Registry) error {

	if o.Prospect != nil {
		if err := o.Prospect.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "prospect")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "prospect")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *PostStopFollowupsBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostStopFollowupsBody) UnmarshalBinary(b []byte) error {
	var res PostStopFollowupsBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*PostStopFollowupsParamsBodyProspect post stop followups params body prospect
swagger:model PostStopFollowupsParamsBodyProspect
*/
type PostStopFollowupsParamsBodyProspect struct {

	// email
	Email string `json:"email,omitempty"`
}

// Validate validates this post stop followups params body prospect
func (o *PostStopFollowupsParamsBodyProspect) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this post stop followups params body prospect based on context it is used
func (o *PostStopFollowupsParamsBodyProspect) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostStopFollowupsParamsBodyProspect) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostStopFollowupsParamsBodyProspect) UnmarshalBinary(b []byte) error {
	var res PostStopFollowupsParamsBodyProspect
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
