// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Campaign campaign
//
// swagger:model Campaign
type Campaign struct {

	// created
	Created string `json:"created,omitempty"`

	// from email
	FromEmail string `json:"from_email,omitempty"`

	// from name
	FromName string `json:"from_name,omitempty"`

	// id
	ID float64 `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// status
	// Enum: [RUNNING PAUSED COMPLETED DRAFT EDITED STOPPED]
	Status string `json:"status,omitempty"`
}

// Validate validates this campaign
func (m *Campaign) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var campaignTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["RUNNING","PAUSED","COMPLETED","DRAFT","EDITED","STOPPED"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		campaignTypeStatusPropEnum = append(campaignTypeStatusPropEnum, v)
	}
}

const (

	// CampaignStatusRUNNING captures enum value "RUNNING"
	CampaignStatusRUNNING string = "RUNNING"

	// CampaignStatusPAUSED captures enum value "PAUSED"
	CampaignStatusPAUSED string = "PAUSED"

	// CampaignStatusCOMPLETED captures enum value "COMPLETED"
	CampaignStatusCOMPLETED string = "COMPLETED"

	// CampaignStatusDRAFT captures enum value "DRAFT"
	CampaignStatusDRAFT string = "DRAFT"

	// CampaignStatusEDITED captures enum value "EDITED"
	CampaignStatusEDITED string = "EDITED"

	// CampaignStatusSTOPPED captures enum value "STOPPED"
	CampaignStatusSTOPPED string = "STOPPED"
)

// prop value enum
func (m *Campaign) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, campaignTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Campaign) validateStatus(formats strfmt.Registry) error {
	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this campaign based on context it is used
func (m *Campaign) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Campaign) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Campaign) UnmarshalBinary(b []byte) error {
	var res Campaign
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
