// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// CreateProspectResponse create prospect response
//
// swagger:model CreateProspectResponse
type CreateProspectResponse struct {
	Status

	// prospects
	Prospects []*CreateProspectResponseProspectsItems0 `json:"prospects"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *CreateProspectResponse) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 Status
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.Status = aO0

	// AO1
	var dataAO1 struct {
		Prospects []*CreateProspectResponseProspectsItems0 `json:"prospects"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.Prospects = dataAO1.Prospects

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m CreateProspectResponse) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.Status)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)
	var dataAO1 struct {
		Prospects []*CreateProspectResponseProspectsItems0 `json:"prospects"`
	}

	dataAO1.Prospects = m.Prospects

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this create prospect response
func (m *CreateProspectResponse) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Status
	if err := m.Status.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProspects(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateProspectResponse) validateProspects(formats strfmt.Registry) error {

	if swag.IsZero(m.Prospects) { // not required
		return nil
	}

	for i := 0; i < len(m.Prospects); i++ {
		if swag.IsZero(m.Prospects[i]) { // not required
			continue
		}

		if m.Prospects[i] != nil {
			if err := m.Prospects[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("prospects" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("prospects" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this create prospect response based on the context it is used
func (m *CreateProspectResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with Status
	if err := m.Status.ContextValidate(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateProspects(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CreateProspectResponse) contextValidateProspects(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Prospects); i++ {

		if m.Prospects[i] != nil {
			if err := m.Prospects[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("prospects" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("prospects" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *CreateProspectResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateProspectResponse) UnmarshalBinary(b []byte) error {
	var res CreateProspectResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// CreateProspectResponseProspectsItems0 create prospect response prospects items0
//
// swagger:model CreateProspectResponseProspectsItems0
type CreateProspectResponseProspectsItems0 struct {

	// email
	Email string `json:"email,omitempty"`
}

// Validate validates this create prospect response prospects items0
func (m *CreateProspectResponseProspectsItems0) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this create prospect response prospects items0 based on context it is used
func (m *CreateProspectResponseProspectsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateProspectResponseProspectsItems0) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateProspectResponseProspectsItems0) UnmarshalBinary(b []byte) error {
	var res CreateProspectResponseProspectsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
